spring.application.name=spring-ecom
spring.datasource.url=jdbc:mysql://localhost:3306/project_ecom
spring.datasource.username=root
spring.datasource.password=12345

# Hibernate configurations for database tables
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jackson.deserialization.fail-on-null-for-primitives=false

# for definning the custom port for application
# server.port=8081  
# for adding a global prefix in api url
# server.servlet.context-path=/api 

spring.security.user.name=admin
spring.security.user.password=123456